---
- name: base
  hosts: localhost
  connection: local
  roles:
  - {role: 'base', tags: 'base'}

- name: mail
  hosts: localhost
  vars_files:
    - /etc/ansible/vars.yml
  connection: local
  roles:
  - {role: 'mail', tags: 'mail'}

- name: nanolist
  hosts: localhost
  vars_files:
    - /etc/ansible/vars.yml
  connection: local
  roles:
  - {role: 'nanolist', tags: 'nanolist'}
